### PR TITLE
Sass file structure

### PR DESCRIPTION
**Pull request by pushpan999**
Created first sass file and folder structure to get started

### CODE REVIEW

**Comment by pushpan999** [comment]
added template file

**Comment by haydenyoung** [comment]
Thanks for the pull request. Before adding, could you provide a basic explanation behind the proposed structure.

**Comment by pushpan999** [comment]
Check template.scss file in sass root folder. You'll see a short hint for every files created....I'll make a note of my idea about managing sass file and will forward it to you asap.

**Comment by haydenyoung** [comment]
Thanks for the update. Just wondering; is there a reason for renaming _template.scss to template.scss (i.e. removing the _)? Sorry for being so pedantic but just want to get the layout and naming correct to keep updating from original bootstrap as simple as possible.

**Comment by pushpan999** [comment]
In sass, the file (name) that have ( _ ) underscore prefix are known as partials which generally means they are/will imported in the main file. The underscore lets Sass know that the file is only a partial file and that it should not be generated into a CSS file. Sass partials are used with the @import directive. In our case template is not the partial file, it's actually a main file that our compiler will use to generate the main css file i.e. template.css

**Pull request closed without merging**
